name: Build and Sign

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Setup certificate
        run: |
          echo "${{ secrets.APPLE_CERTIFICATE_BASE64 }}" | base64 --decode > certificate.p12
          security create-keychain -p temp build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p temp build.keychain
          security import certificate.p12 -k build.keychain -P "${{ secrets.APPLE_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k temp build.keychain

      - name: Build
        run: |
          xcodebuild -project LearningSwift.xcodeproj -scheme LearningSwift -configuration Release -derivedDataPath build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LearningSwift-unsigned
          path: build/Build/Products/Release/LearningSwift.app
